# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = laserMarking
DESTDIR = ./x64/Release
CONFIG += debug
LIBS += -L"." \
    -lshape_match_dll
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += release
UI_DIR += .
RCC_DIR += .
include(laserMarking.pri)
